# Config file for automatic testing at travis-ci.org
sudo: false  # http://docs.travis-ci.com/user/migrating-from-legacy/
language: python
python:
  - "3.6"
install:
  - pip install --extra-index-url https://teampypi.herokuapp.com/ team.datasync
  - pip install -r requirements.txt
before_script:
  - export DEBUG=1
  - export APP_SETTINGS_IMAGESYNC=test 

script: nosetests -v

deploy:
      provider: pypi
      user: team
      password: team
      server: https://teampypi.herokuapp.com/
